server:
  port: 8002

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://vps.dluserver.cn:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test_db
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    instance-id: user-service-8002
    # 访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 单机版
        #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
